### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [MJeekhof/theScoop#1]
Grade: Needs Improvement

I'm a bit confused because I see that you added the necessary routes to the routes object, but I'm not sure where you actually implement them. Please do that and resubmit!

**Comment by MJeekhof** [comment]
Should I create separate documents for the routes, or is that not part of the assignment? For now I've added basic express routes in server.js.

**Comment by MJeekhof** [comment]
Hi @blerude, I've refactored the routes and added a function. Its quite difficult to think in line of the assignment, after completing the other assignments. Please let me know if I'm writing any sense-able code. cheers, mike

**Comment by blerude** [comment]
Hi Mike,

You are off to a good start! Your createComment function is coming along and you are correct to have put it in the server.js file. I encourage you to continue by implementing the remaining routes for the assignment (update, delete, downvote, and upvoteComment).

**Comment by MJeekhof** [comment]
Hi @blerude Thanks for your review! I've given it more thought and submitted it again. Please let me know if I'm stearing towards the finish line or walking backwards:P

**Comment by blerude** [comment]
Looks good! My only final suggestion would be that in the deleteComment function, you also need to delete the comment from the article that it refers to. Great job!

**Comment by MJeekhof** [comment]
Hi @blerude  Awesome! hmm... just made an educated guess on that, hope its a bullseye:)

`// Deletes a specific comment
function deleteComment(url, request) {
  const id = Number(url.split('/').filter(segment => segment)[1]);
  const savedComment = database.comments[id];
  const response = {};

  if (savedComment) {
    database.comments[id] = null;
    savedComment.commentIds.forEach(commentId => {
      const article = database.Articles[articleId];
      database.articles[articleId] = null;
      const userArticleIds = database.users[article.username].articleIds;
      userArticleIds.splice(userArticleIds.indexOf(id), 1);
    });
    const userCommentIds = database.users[savedComment.username].commentIds;
    userCommentIds.splice(userCommentIds.indexOf(id), 1);
    response.status = 204;
  } else {
    response.status = 400;
  }

  return response;
}`

**Comment by blerude** [comment]
That's right, you got it!
